//
// Created by lebonq on 23/12/22.
//

#ifndef PROJET_DM_QUENTIN_LEBON_INTERACTIVEOBJECT_HPP
#define PROJET_DM_QUENTIN_LEBON_INTERACTIVEOBJECT_HPP

class InteractiveObject {
};

#endif // PROJET_DM_QUENTIN_LEBON_INTERACTIVEOBJECT_HPP
