//
// Created by lebonq on 20/12/22.
//

#ifndef PROJET_DM_QUENTIN_LEBON_SHADERSMANAGER_HPP
#define PROJET_DM_QUENTIN_LEBON_SHADERSMANAGER_HPP

class ShadersManager {
};

#endif // PROJET_DM_QUENTIN_LEBON_SHADERSMANAGER_HPP
