//
// Created by lebonq on 23/12/22.
//

#ifndef PROJET_DM_QUENTIN_LEBON_WORLDOBJECT_HPP
#define PROJET_DM_QUENTIN_LEBON_WORLDOBJECT_HPP

class WorldObject {
};

#endif // PROJET_DM_QUENTIN_LEBON_WORLDOBJECT_HPP
